version: "3"
services: 
    postgres:
        image: postgres
        environment: 
            POSTGRES_PASSWORD: password1!
            POSTGRES_USER: admin
            POSTGRES_DB: App
        volumes: 
            - postgres-data:/var/lib/postgresql/data
        ports: 
            - 5432:5432

volumes: 
    postgres-data: