version: "3"
services: 
    postgres:
        image: postgres
        environment: 
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: password1!
            POSTGRES_DB: App
        volumes: 
            - postgres-data:/var/lib/postgresql/data
        ports: 
            - 5432:5432
    mongo: 
        image: mongo
        environment: 
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: password1!
        ports: 
            - 27017:27017
        volumes: 
            - mongo-data:/data/db
    redis:
        image: redis
        ports:
            - 6379:6379
    zookeeper:
        image: wurstmeister/zookeeper
        ports:
        - "2181"
        hostname: zookeeper
    kafka:
        image: wurstmeister/kafka
        ports:
        - "9092:9092"
        hostname: kafka
        environment:
            KAFKA_CREATE_TOPICS: "UploadFile:1:1"
            KAFKA_ADVERTISED_HOST_NAME: kafka
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_ADVERTISED_PORT: 9092
        volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        depends_on:
        - "zookeeper"


volumes: 
    postgres-data:
    mongo-data: