version: "3"
services: 
    postgres:
        image: postgres
        environment: 
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: password1!
            POSTGRES_DB: App
        volumes: 
            # - ./bin/init.sql:/docker-entrypoint-initdb.d/init.sql
            - postgres-data:/var/lib/postgresql/data
        ports: 
            - 5432:5432
    mongo: 
        image: mongo
        environment: 
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: password1!
        ports: 
            - 27017:27017
        volumes: 
            - mongo-data:/data/db
    redis:
        image: redis
        ports:
            - 6379:6379
    zookeeper:
        image: wurstmeister/zookeeper
        ports:
        - "2181:2181"
        hostname: zookeeper
    kafka:
        image: wurstmeister/kafka
        ports:
        - 29092:29092
        environment:
            KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:29092
            KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:29092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE      
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_MESSAGE_MAX_BYTES: 500000000
        depends_on:
        - "zookeeper"
    api:
        build: ./api
        ports:
            - "3000:3000"

volumes: 
    postgres-data:
    mongo-data: